### PR TITLE
Improved sideloaded support

### PR DESCRIPTION
**Pull request by nicknitewolf**
Also add a cflag -DJAILED to compile jailed version

### CODE REVIEW

**Comment by nicknitewolf** [comment]
Thanks @Luewii for the modifications required. I'm not sure whether a symlink is enough for the original resources

**Comment by Galactic-Dev** [comment]
Where is the bundle stored, because it would get overwritten when you update the YouTube app correct?

**Comment by nicknitewolf** [comment]
> Where is the bundle stored, because it would get overwritten when you update the YouTube app correct?

This is for sideloading only. Everytime we update the app, we have to inject the dylib as well as the bundle

**Comment by Galactic-Dev** [comment]
Ok, so only if a certain cflag is enabled it will compile this way. So I can pull this without it effecting the main tweak.

**Comment by nicknitewolf** [comment]
> Ok, so only if a certain cflag is enabled it will compile this way. So I can pull this without it effecting the main tweak.

Yes. to make the jailed version you have to run
`make package FINALPACKAGE=1 JAILED=1`

**Comment by nicknitewolf** [comment]
I'm more worried that my symlink of Resources/ will not be copied over to layout (root)

**Comment by Galactic-Dev** [comment]
I'll test it out then pull if it works out.

**Comment by nicknitewolf** [comment]
It should work this time... I changed to using internal-stage since I realised the symlink will get easily destroyed with each update

**Comment by Luewii** [comment]
Greetings! If I can chime in and express/address the same concern as @Galactic-Dev. An ideal solution would be to only have to compile the tweak once without any extra flags for both jailed and jailbroken states. I have not updated my branch in a while and as it stands it worked by injecting the resources in the Youtube.app (main bundle) where the main binaries and frameworks are. Assuming the proposed solution is anything like my branch, if a jailbroken user updates the Youtube via the appstore, the update would in theory overwrite the tweak. To overcome this, the tweak resources would be better off saved in Youtube's data container, (where caches and temp data is stored) as it would survive an update via the appstore. Cercube does something like this in where a folder called 'Carida_Files' is created in '/Application/YouTube/Documents/' for both jailed and jailbroken users and it is the same tweak for both and not a different variation. If something similar can be done for this tweak, it would be a single solution that satisfies both jailed and jailbroken users without having to compile based on whether a user is jailed or jailbroken.

**Comment by nicknitewolf** [comment]
> Greetings! If I can chime in and express/address the same concern as @Galactic-Dev. An ideal solution would be to only have to compile the tweak once without any extra flags for both jailed and jailbroken states. I have not updated my branch in a while and as it stands it worked by injecting the resources in the Youtube.app (main bundle) where the main binaries and frameworks are. Assuming the proposed solution is anything like my branch, if a jailbroken user updates the Youtube via the appstore, the update would in theory overwrite the tweak. To overcome this, the tweak resources would be better off saved in Youtube's data container, (where caches and temp data is stored) as it would survive an update via the appstore. Cercube does something like this in where a folder called 'Carida_Files' is created in '/Application/YouTube/Documents/' for both jailed and jailbroken users and it is the same tweak for both and not a different variation. If something similar can be done for this tweak, it would be a single solution that satisfies both jailed and jailbroken users without having to compile based on whether a user is jailed or jailbroken.

Ah yes this sounds sane. So something like:
```
NSString *bundleID = @"com.google.ios.youtube";
LSApplicationWorkspace *workspace = [LSApplicationWorkspace defaultWorkspace];
LSApplicationProxy *app = [LSApplicationProxy applicationProxyForIdentifier:bundleID];
if ([[app appState] isValid]) {
    printf("Container Path: %s\n", [[app containerURL] fileSystemRepresentation]);
}
```

**Comment by Luewii** [comment]
I suppose. Another thing to consider is what would happen to the resources if a jailbroken uninstall then reinstalls YT (no upgrade)? Would the resources persist or would reinstalling the tweak be necessary?

**Comment by Luewii** [comment]
Maybe your original proposal is the best solution at the moment I would just suggest documenting in the readme.

**Comment by nicknitewolf** [comment]
I'm not sure if this would work. I am checking whether the files exist in the documents container before copying it

**Comment by nicknitewolf** [comment]
I just realised another issue. If you sideload cercube, the dylib will not be detected

**Comment by Galactic-Dev** [comment]
> Greetings! If I can chime in and express/address the same concern as @Galactic-Dev. An ideal solution would be to only have to compile the tweak once without any extra flags for both jailed and jailbroken states. I have not updated my branch in a while and as it stands it worked by injecting the resources in the Youtube.app (main bundle) where the main binaries and frameworks are. Assuming the proposed solution is anything like my branch, if a jailbroken user updates the Youtube via the appstore, the update would in theory overwrite the tweak. To overcome this, the tweak resources would be better off saved in Youtube's data container, (where caches and temp data is stored) as it would survive an update via the appstore. Cercube does something like this in where a folder called 'Carida_Files' is created in '/Application/YouTube/Documents/' for both jailed and jailbroken users and it is the same tweak for both and not a different variation. If something similar can be done for this tweak, it would be a single solution that satisfies both jailed and jailbroken users without having to compile based on whether a user is jailed or jailbroken.

I could easily migrate the tweak to do this, as I already store the iSponsorBlock prefs plist in that same directory.

**Comment by nicknitewolf** [comment]
> > Greetings! If I can chime in and express/address the same concern as @Galactic-Dev. An ideal solution would be to only have to compile the tweak once without any extra flags for both jailed and jailbroken states. I have not updated my branch in a while and as it stands it worked by injecting the resources in the Youtube.app (main bundle) where the main binaries and frameworks are. Assuming the proposed solution is anything like my branch, if a jailbroken user updates the Youtube via the appstore, the update would in theory overwrite the tweak. To overcome this, the tweak resources would be better off saved in Youtube's data container, (where caches and temp data is stored) as it would survive an update via the appstore. Cercube does something like this in where a folder called 'Carida_Files' is created in '/Application/YouTube/Documents/' for both jailed and jailbroken users and it is the same tweak for both and not a different variation. If something similar can be done for this tweak, it would be a single solution that satisfies both jailed and jailbroken users without having to compile based on whether a user is jailed or jailbroken.
> 
> I could easily migrate the tweak to do this, as I already store the iSponsorBlock prefs plist in that same directory.

Alright my latest commit should do this, although I did create a new directory

**Pull request closed without merging**
